site_name: TSSR Documentation & Lab Vault
site_description: TSSR Lab Runbooks, Configs, and Notes
site_url: https://natalshadow.github.io/TSSR_Doc/

theme:
  name: material
  palette:
    scheme: slate # Dark theme
    primary: indigo
    accent: blue
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

plugins:
  - search
  - roamlinks
  - callouts

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

docs_dir: docs